### ISSUE TITLE
Models especially at higher sink Temperature fails (Singularity in Jacobian matrix)

### ISSUE THREAD

**Issue by bilwint** [jfreissmann/heatpumps#21]
In all models when the the Sink temperature goes beyond particular temperature system fails to solve. For example, when the working fluid is NH3, if `Temperature Rücklauf` is greater than or equal to `100°C`, solver fails to find the solution. Here, `Teperature Vorlauf` is not an issue. It can be any value less than `T_crit`.

**Comment by bilwint** [comment]
@jfreissmann 
I went through this issue. And I found out that when we assign temperature value to the connection `C1`, instead of `C0`, we can avoid this issue and will get the solution. So I am planned to do the following changes.

1. in all models `self.conns['C1'].set_attr(T=self.params['C1']['T'])`
2. In params change `C0` to `C1`
3. In dashboard update the `Temperature Rücklauf` user input to `params['C1']['T]`

or 

Simply `self.conns['C1'].set_attr(T=self.params['C0']['T'])` without modifying others.

Or any other solution for better starting values to solve the system. What do you think ?

**Comment by bilwint** [comment]
yes, I observed this in multiple in models. I tried each model from each Grundtopologie. The same problem exists.

**Comment by jfreissmann** [comment]
Okay, then let's change it to `'C1'`. Are you inclined or should I do it? I am open to both options.

I am loosely planning to build some automated tests, so that we do not have to do it manually each time. Hopefully there will be time for that soon.

**Comment by bilwint** [comment]
ok, I will do

**Comment by jfreissmann** [comment]
Resolved with PR #22.
