### ISSUE TITLE
Changing the scale of the axes of the process diagrams does not work

### ISSUE THREAD

**Issue by fwitte** [jfreissmann/heatpumps#24]
When I try to change the scales for the process diagrams, the app "reloads" and I have to click on "Auslegung ausführen" again with the values reset. Ideally, only the diagrams would update.

**Comment by jfreissmann** [comment]
Hey @fwitte,

thank you for reporting the issue. It was likely introduced while fixing another issue when reloading the main page in design mode and stems from the way `streamlit` reloads the whole page on change. We will either have to find a way to avoid this reload or make the streamlit-side axes scaling obsolete within the implementation of `plotly` diagrams as discussed in issue #27.

**Comment by jfreissmann** [comment]
For now, the axes limit sliders are removed, as we now have great default limits. Interactivity could return when plotly is implemented in `fluprodia`. Until then, this issue can be closed I think.
